# Scripts Notebook

#### Import packages

In [1]:
import pandas as pd

#### Set file paths for input file "Lista Equivalentes" and output files "TCA" and "Equivalentes"

In [9]:
input_path = "Lista Equivalentes.xlsx"
output_path_tca = "TCA.json"
output_path_equivalentes_detalhe = "EquivalentesDetalhe.json"
output_path_equivalentes = "Equivalentes.json"

#### Import relevant sheets from workbook

TCA

In [3]:
df1 = pd.read_excel(input_path,engine='openpyxl',sheet_name='TCA',usecols='A:AV')
df1.head()

,Nome do alimento,Source,Código INSA,Nível 1,Nível 2,Nível 3,Energia (kcal),Energia (kJ),Lípidos (g),Ácidos gordos saturados (g),...,Cinza (g),Sódio (mg),Potássio (mg),Cálcio (mg),Fósforo (mg),Magnésio (mg),Ferro (mg),Zinco (mg),Selénio (µg),Iodo (µg)
0,"Abacate, Hass",INSA,624,Frutos e produtos derivados de frutos,Fruta utilizada como fruta,"Frutos diversos com casca não comestível, grandes",176.0,726.0,17.4,4.2,...,0.75,15.0,330.0,4.0,36.0,21.0,0.3,0.3,NaN,NaN
1,Abacaxi,Alimentos Extra,na,Fruta e produtos da fruta,NaN,NaN,NaN,NaN,0.1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Abóbora cristalizada,INSA,625,Produtos hortícolas e derivados,Produtos hortícolas transformados ou em conser...,Produtos hortícolas cristalizados ou conservad...,293.0,1240.0,0.2,0.1,...,0.15,27.0,22.0,28.0,2.0,3.0,0.4,0.1,NaN,NaN
3,Abóbora crua,INSA,579,Produtos hortícolas e derivados,Frutos de hortícolas,Frutos vegetais de cucurbitáceas,11.0,47.0,0.2,0.1,...,0.40,1.0,200.0,25.0,5.0,5.0,0.1,0.1,NaN,NaN
4,Abrótea cozida,INSA,801,"Peixes, mariscos, anfíbios, répteis e inverteb...",Peixe (músculo),Peixe de mar,79.0,334.0,0.1,0.0,...,2.00,360.0,360.0,13.0,270.0,36.0,0.2,0.6,NaN,22.0

In [4]:
# df1.dtypes

Equivalentes

In [5]:
df2 = pd.read_excel(input_path,engine='openpyxl',sheet_name='Equivalentes',usecols='A:F')
df2.head()

,Grupo,Nome,Alimento,Porcao,Plano,Medida Caseira
0,Outros,Açúcares,Açúcar amarelo,15,NaN,1 colher de sobremesa
1,Outros,Açúcares,Açúcar branco,15,NaN,1 colher de sobremesa
2,Gorduras,Azeitona e Abacate,"Abacate, Hass",30,NaN,1 metade
3,Gorduras,Azeitona e Abacate,Azeitona,30,NaN,NaN
4,Hidratos I,Bebida de soja,"Bebida à base de soja com açúcar, com cálcio, ...",240,Nao,1 copo

In [6]:
# df2.dtypes

In [7]:
df3 = pd.merge(df2,df1,how='inner',left_on='Alimento',right_on='Nome do alimento').groupby(by=['Grupo','Nome'])[['Porcao','Lípidos (g)','Hidratos de carbono (g)','Proteínas (g)','Álcool (g)']].mean()
df3['Energia (kcal)'] = df3['Lípidos (g)'] * 9 + df3['Hidratos de carbono (g)'] * 4 + df3['Proteínas (g)'] * 4 + df3['Álcool (g)'] * 7
df3['Hidratos (g) Porcao'] = df3['Hidratos de carbono (g)'] * df3['Porcao'] / 100
df3['Lípidos (g) Porcao'] = df3['Lípidos (g)'] * df3['Porcao'] / 100
df3['Proteínas (g) Porcao'] = df3['Proteínas (g)'] * df3['Porcao'] / 100
df3['Álcool (g) Porcao'] = df3['Álcool (g)'] * df3['Porcao'] / 100
df3.reset_index(inplace=True)
df3

,Grupo,Nome,Porcao,Lípidos (g),Hidratos de carbono (g),Proteínas (g),Álcool (g),Energia (kcal),Hidratos (g) Porcao,Lípidos (g) Porcao,Proteínas (g) Porcao,Álcool (g) Porcao
0,Gorduras,Azeitona e Abacate,30.000000,17.950000,1.150000,1.250000,0.000000,171.150000,0.345000,5.385000,0.375000,0.000000
1,Gorduras,Frutos Gordos,19.117647,51.223529,12.229412,17.200000,0.000000,578.729412,2.337976,9.792734,3.288235,0.000000
2,Gorduras,Gorduras e óleos,5.000000,99.600000,0.000000,0.000000,0.000000,896.400000,0.000000,4.980000,0.000000,0.000000
3,Gorduras,Manteiga de frutos gordos,20.000000,50.000000,7.000000,30.000000,0.000000,598.000000,1.400000,10.000000,6.000000,0.000000
4,Gorduras,Manteiga e cremes light,10.000000,42.850000,1.225000,1.125000,0.000000,395.050000,0.122500,4.285000,0.112500,0.000000
5,Hidratos I,Bebida de soja,240.000000,2.166667,3.666667,3.700000,0.000000,48.966667,8.800000,5.200000,8.880000,0.000000
6,Hidratos I,Fruta (100g),100.000000,0.307407,10.048148,0.707407,0.000000,45.788889,10.048148,0.307407,0.707407,0.000000
7,Hidratos I,Fruta (200g),175.000000,0.350000,6.400000,0.666667,0.000000,31.416667,11.200000,0.612500,1.166667,0.000000
8,Hidratos I,Fruta (50g),46.666667,0.416667,20.866667,0.766667,0.000000,90.283333,9.737778,0.194444,0.357778,0.000000
9,Hidratos I,Iogurtes proteicos magros,182.500000,0.150000,6.850000,9.650000,0.000000,67.350000,12.501250,0.273750,17.611250,0.000000
10,Hidratos I,Legumes (100g),100.000000,0.464516,3.532258,2.009677,0.000000,26.348387,3.532258,0.464516,2.009677,0.000000
11,Hidratos I,Legumes (consumo livre),100.000000,0.395833,1.262500,1.933333,0.000000,16.345833,1.262500,0.395833,1.933333,0.000000
12,Hidratos I,Leite Gordo,240.000000,3.475000,4.700000,3.025000,0.000000,62.175000,11.280000,8.340000,7.260000,0.000000
13,Hidratos I,Leite e iogurte MG,244.000000,1.600000,4.900000,3.520000,0.000000,48.080000,11.956000,3.904000,8.588800,0.000000
14,Hidratos I,Leite e iogurte magros,240.000000,0.388889,4.944444,4.122222,0.000000,39.766667,11.866667,0.933333,9.893333,0.000000
15,Hidratos I,Queijo MG,35.000000,21.960000,2.920000,17.240000,0.000000,278.280000,1.022000,7.686000,6.034000,0.000000
16,Hidratos I,Queijo magro,30.000000,8.366667,3.100000,22.300000,0.000000,176.900000,0.930000,2.510000,6.690000,0.000000
17,Hidratos I,Soja,60.000000,7.500000,5.600000,12.500000,0.000000,139.900000,3.360000,4.500000,7.500000,0.000000
18,Hidratos I,Sopa,250.000000,1.513514,5.156757,1.591892,0.000000,40.616216,12.891892,3.783784,3.979730,0.000000
19,Hidratos II,Bolacha,20.000000,15.737500,65.037500,9.250000,0.000000,438.787500,13.007500,3.147500,1.850000,0.000000
20,Hidratos II,Bolacha de Milho ou Arroz,20.000000,2.750000,81.750000,7.900000,0.000000,383.350000,16.350000,0.550000,1.580000,0.000000
21,Hidratos II,Cereais e granola,21.818182,2.709091,68.400000,10.600000,0.000000,340.381818,14.923636,0.591074,2.312727,0.000000
22,Hidratos II,Guarnição,50.000000,1.102222,28.183333,3.990000,0.000000,138.613333,14.091667,0.551111,1.995000,0.000000
23,Hidratos II,Pão,27.916667,2.850000,55.566667,9.433333,0.000000,285.650000,15.512361,0.795625,2.633472,0.000000
24,Leguminosas,Leguminosas,75.000000,0.975000,12.175000,8.866667,0.000000,92.941667,9.131250,0.731250,6.650000,0.000000
25,Outros,Açúcares,15.000000,0.000000,98.400000,0.000000,0.000000,393.600000,14.760000,0.000000,0.000000,0.000000
26,Outros,Compotas,25.000000,0.020000,56.060000,0.400000,0.000000,226.020000,14.015000,0.005000,0.100000,0.000000
27,Outros,Farinhas,20.000000,2.545455,71.000000,9.536364,0.000000,345.054545,14.200000,0.509091,1.907273,0.000000
28,Outros,Vinho ou Cerveja,172.222222,0.000000,0.855556,0.155556,7.222222,54.600000,1.473457,0.000000,0.267901,12.438272
29,Proteínas,Carne e Peixe,30.000000,6.754412,0.080882,24.427941,0.000000,158.825000,0.024265,2.026324,7.328382,0.000000
30,Proteínas,Fiambre de aves,50.000000,2.350000,2.350000,14.150000,0.000000,87.150000,1.175000,1.175000,7.075000,0.000000
31,Proteínas,Ovos,60.000000,10.333333,0.000000,12.633333,0.000000,143.533333,0.000000,6.200000,7.580000,0.000000
32,Proteínas,Peixes gordos,30.000000,12.215385,0.046154,22.869231,0.000000,201.600000,0.013846,3.664615,6.860769,0.000000
33,Proteínas,Tofu,60.000000,4.400000,0.700000,8.500000,0.000000,76.400000,0.420000,2.640000,5.100000,0.000000
34,Proteínas,Whey e proteína vegetal,15.000000,4.650000,3.675000,83.600000,0.000000,390.950000,0.551250,0.697500,12.540000,0.000000

In [8]:
df1.to_json(output_path_tca,orient='records')
df2.to_json(output_path_equivalentes_detalhe,orient='records')
df3.to_json(output_path_equivalentes,orient='records')

# THE END