# Scripts Notebook

#### Import packages

In [1]:
import pandas as pd

#### Set file paths for input file "Lista Equivalentes" and output files "TCA" and "Equivalentes"

In [2]:
input_path = "Lista Equivalentes.xlsx"
output_path_tca = "TCA.json"
output_path_equivalentes_detalhe = "EquivalentesDetalhe.json"
output_path_equivalentes = "Equivalentes.json"
output_path_equivalentes_csv = "Equivalentes.csv"
output_path_equivalentes_resumo_csv = "EquivalentesResumo.csv"

#### Import relevant sheets from workbook

TCA

In [3]:
df1 = pd.read_excel(input_path,engine='openpyxl',sheet_name='TCA',usecols='A:AV')
df1.head()

,Nome do alimento,Source,Código INSA,Nível 1,Nível 2,Nível 3,Energia (kcal),Energia (kJ),Lípidos (g),Ácidos gordos saturados (g),...,Cinza (g),Sódio (mg),Potássio (mg),Cálcio (mg),Fósforo (mg),Magnésio (mg),Ferro (mg),Zinco (mg),Selénio (µg),Iodo (µg)
0,"Abacate, Hass",INSA,624,Frutos e produtos derivados de frutos,Fruta utilizada como fruta,"Frutos diversos com casca não comestível, grandes",176.0,726.0,17.4,4.2,...,0.75,15.0,330.0,4.0,36.0,21.0,0.3,0.3,NaN,NaN
1,Abacaxi,Alimentos Extra,na,Fruta e produtos da fruta,NaN,NaN,NaN,NaN,0.1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Abóbora cristalizada,INSA,625,Produtos hortícolas e derivados,Produtos hortícolas transformados ou em conser...,Produtos hortícolas cristalizados ou conservad...,293.0,1240.0,0.2,0.1,...,0.15,27.0,22.0,28.0,2.0,3.0,0.4,0.1,NaN,NaN
3,Abóbora crua,INSA,579,Produtos hortícolas e derivados,Frutos de hortícolas,Frutos vegetais de cucurbitáceas,11.0,47.0,0.2,0.1,...,0.40,1.0,200.0,25.0,5.0,5.0,0.1,0.1,NaN,NaN
4,Abrótea cozida,INSA,801,"Peixes, mariscos, anfíbios, répteis e inverteb...",Peixe (músculo),Peixe de mar,79.0,334.0,0.1,0.0,...,2.00,360.0,360.0,13.0,270.0,36.0,0.2,0.6,NaN,22.0

In [4]:
# df1.dtypes

Equivalentes

In [5]:
df2 = pd.read_excel(input_path,engine='openpyxl',sheet_name='Equivalentes',usecols='A:G')
df2

,Grupo,Nome,Alimento,Porcao,Media,Plano,Medida Caseira
0,Outros,Açúcares,Açúcar amarelo,15,Sim,Nao,1 colher de sobremesa
1,Outros,Açúcares,Açúcar branco,15,Sim,Sim,1 colher de sobremesa
2,Gorduras,Azeitona e Abacate,"Abacate, Hass",25,Sim,Sim,1 metade
3,Gorduras,Azeitona e Abacate,Azeitona,25,Sim,Nao,NaN
4,Hidratos I,Bebida de soja,"Bebida à base de soja com açúcar, com cálcio, ...",240,Sim,Nao,1 copo
...,...,...,...,...,...,...,...
376,Outros,Vinho ou Cerveja,Vinho verde tinto,150,Sim,NaN,NaN
377,Proteínas,Whey e proteína vegetal,Proteína Arroz Integral,15,Sim,NaN,NaN
378,Proteínas,Whey e proteína vegetal,Proteína Whey (aromatizada),15,Sim,NaN,NaN
379,Proteínas,Whey e proteína vegetal,Proteína Whey (isolada),15,Sim,NaN,NaN
380,Proteínas,Whey e proteína vegetal,Proteína Whey (sem sabor),15,Sim,NaN,NaN

In [6]:
df2_filter = df2[df2['Media'] == 'Sim']
df2_filter

,Grupo,Nome,Alimento,Porcao,Media,Plano,Medida Caseira
0,Outros,Açúcares,Açúcar amarelo,15,Sim,Nao,1 colher de sobremesa
1,Outros,Açúcares,Açúcar branco,15,Sim,Sim,1 colher de sobremesa
2,Gorduras,Azeitona e Abacate,"Abacate, Hass",25,Sim,Sim,1 metade
3,Gorduras,Azeitona e Abacate,Azeitona,25,Sim,Nao,NaN
4,Hidratos I,Bebida de soja,"Bebida à base de soja com açúcar, com cálcio, ...",240,Sim,Nao,1 copo
...,...,...,...,...,...,...,...
376,Outros,Vinho ou Cerveja,Vinho verde tinto,150,Sim,NaN,NaN
377,Proteínas,Whey e proteína vegetal,Proteína Arroz Integral,15,Sim,NaN,NaN
378,Proteínas,Whey e proteína vegetal,Proteína Whey (aromatizada),15,Sim,NaN,NaN
379,Proteínas,Whey e proteína vegetal,Proteína Whey (isolada),15,Sim,NaN,NaN
380,Proteínas,Whey e proteína vegetal,Proteína Whey (sem sabor),15,Sim,NaN,NaN

In [20]:
df3 = pd.merge(df2,df1,how='inner',left_on='Alimento',right_on='Nome do alimento')
df3['Energia (kcal)'] = df3['Lípidos (g)'] * 9 + df3['Hidratos de carbono (g)'] * 4 + df3['Proteínas (g)'] * 4 + df3['Álcool (g)'] * 7
df3['Hidratos (g) Porcao'] = df3['Hidratos de carbono (g)'] * df3['Porcao'] / 100
df3['Lípidos (g) Porcao'] = df3['Lípidos (g)'] * df3['Porcao'] / 100
df3['Proteínas (g) Porcao'] = df3['Proteínas (g)'] * df3['Porcao'] / 100
df3['Álcool (g) Porcao'] = df3['Álcool (g)'] * df3['Porcao'] / 100
df3_grouped = df3.groupby(by=['Grupo','Nome'])[['Porcao','Lípidos (g) Porcao','Hidratos (g) Porcao','Proteínas (g) Porcao','Álcool (g) Porcao']].mean()
df3_grouped.reset_index(inplace=True)
df3_grouped

,Grupo,Nome,Porcao,Lípidos (g) Porcao,Hidratos (g) Porcao,Proteínas (g) Porcao,Álcool (g) Porcao
0,Gorduras,Azeitona e Abacate,25.000000,4.487500,0.287500,0.312500,0.000000
1,Gorduras,Frutos Gordos,10.000000,5.949167,0.780000,1.855833,0.000000
2,Gorduras,Gorduras e óleos,6.666667,6.066667,0.023333,0.003333,0.000000
3,Gorduras,Manteiga de frutos gordos,10.000000,5.000000,0.700000,3.000000,0.000000
4,Gorduras,Manteiga e cremes light,10.000000,4.285000,0.122500,0.112500,0.000000
5,Hidratos I,Bebida de soja,240.000000,5.200000,8.800000,8.880000,0.000000
6,Hidratos I,Bebida vegetal sem açúcar,240.000000,2.640000,0.240000,0.960000,0.000000
7,Hidratos I,Fruta (100g),100.000000,0.307407,10.048148,0.707407,0.000000
8,Hidratos I,Fruta (200g),175.000000,0.637500,8.987500,1.220833,0.000000
9,Hidratos I,Fruta (50g),46.666667,0.205000,9.326667,0.343333,0.000000
10,Hidratos I,Iogurtes proteicos magros,170.000000,0.360000,9.650000,16.860000,0.000000
11,Hidratos I,Legumes (100g),100.000000,0.464516,3.532258,2.009677,0.000000
12,Hidratos I,Legumes (consumo livre),100.000000,0.395833,1.262500,1.933333,0.000000
13,Hidratos I,Leite Gordo,240.000000,8.340000,11.280000,7.260000,0.000000
14,Hidratos I,Leite e iogurte MG,244.000000,3.906000,11.950000,8.608000,0.000000
15,Hidratos I,Leite e iogurte magros,240.000000,0.933333,11.866667,9.893333,0.000000
16,Hidratos I,Queijo MG,35.000000,7.424000,1.045000,5.785000,0.000000
17,Hidratos I,Queijo magro,30.000000,1.853333,1.310000,5.760000,0.000000
18,Hidratos I,Sopa,250.000000,3.783784,12.891892,3.979730,0.000000
19,Hidratos II,Bolacha,20.000000,3.147500,13.007500,1.850000,0.000000
20,Hidratos II,Bolacha de Milho ou Arroz,20.000000,0.550000,16.350000,1.580000,0.000000
21,Hidratos II,Cereais e granola,20.000000,0.541818,13.680000,2.120000,0.000000
22,Hidratos II,Guarnição,55.555556,0.576889,13.994444,1.856222,0.000000
23,Hidratos II,Pão,27.916667,0.770417,15.197500,2.577500,0.000000
24,Leguminosas,Leguminosas,75.000000,0.660000,9.380000,6.283333,0.000000
25,Outros,Açúcares,15.000000,0.000000,14.760000,0.000000,0.000000
26,Outros,Claras,55.000000,0.082500,0.275000,5.912500,0.000000
27,Outros,Compotas,25.000000,0.005000,14.015000,0.100000,0.000000
28,Outros,Farinhas,20.000000,0.509091,14.200000,1.907273,0.000000
29,Outros,Fruta desidratada,15.000000,0.272500,9.090000,0.550833,0.000000
30,Outros,Vinho ou Cerveja,172.222222,0.000000,1.600000,0.283333,11.794444
31,Proteínas,Carne e Peixe,30.000000,1.617500,0.021000,7.290000,0.000000
32,Proteínas,Fiambre de aves,50.000000,1.175000,1.175000,7.075000,0.000000
33,Proteínas,Ovos,60.000000,6.200000,0.000000,7.580000,0.000000
34,Proteínas,Peixes gordos,30.000000,3.664615,0.013846,6.860769,0.000000
35,Proteínas,Soja,60.000000,4.500000,3.360000,7.500000,0.000000
36,Proteínas,Tofu,60.000000,2.640000,0.420000,5.100000,0.000000
37,Proteínas,Whey e proteína vegetal,15.000000,0.697500,0.551250,12.540000,0.000000

In [17]:
df4 = pd.merge(df2_filter,df1,how='inner',left_on='Alimento',right_on='Nome do alimento')
df4['Energia (kcal)'] = df4['Lípidos (g)'] * 9 + df4['Hidratos de carbono (g)'] * 4 + df4['Proteínas (g)'] * 4 + df4['Álcool (g)'] * 7
df4['Hidratos (g) Porcao'] = df4['Hidratos de carbono (g)'] * df4['Porcao'] / 100
df4['Lípidos (g) Porcao'] = df4['Lípidos (g)'] * df4['Porcao'] / 100
df4['Proteínas (g) Porcao'] = df4['Proteínas (g)'] * df4['Porcao'] / 100
df4['Álcool (g) Porcao'] = df4['Álcool (g)'] * df4['Porcao'] / 100
df5 = df4.groupby(by=['Grupo'])[['Porcao','Lípidos (g) Porcao','Hidratos (g) Porcao','Proteínas (g) Porcao','Álcool (g) Porcao']].mean()
df6 = df5.round(decimals={
                    'Porcao':0,
                    'Lípidos (g) Porcao':1,
                    'Hidratos (g) Porcao':1,
                    'Proteínas (g) Porcao':1,
                    'Álcool (g) Porcao':1
                    })
df6.reset_index(inplace=True)
df6

,Grupo,Porcao,Lípidos (g) Porcao,Hidratos (g) Porcao,Proteínas (g) Porcao,Álcool (g) Porcao
0,Gorduras,10.0,5.3,0.5,1.1,0.0
1,Hidratos I,151.0,1.8,7.9,3.3,0.0
2,Hidratos II,30.0,1.1,14.2,2.1,0.0
3,Leguminosas,75.0,0.7,9.4,6.3,0.0
4,Outros,49.0,0.2,9.2,1.0,2.3
5,Proteínas,32.0,2.1,0.1,7.4,0.0

In [21]:
df1.to_json(output_path_tca,orient='records')
df2.to_json(output_path_equivalentes_detalhe,orient='records')
df3.to_json(output_path_equivalentes,orient='records')
df3_grouped.to_csv(output_path_equivalentes_csv,sep=',',decimal='.',encoding='utf-8')
df6.to_csv(output_path_equivalentes_resumo_csv,sep=',',decimal='.',encoding='utf-8')

# THE END